require 'absolute_renamer/interpreters/counter_interpreter'
require 'absolute_renamer/interpreters/filename_parts_interpreter'
require 'absolute_renamer/interpreters/original_filename_interpreter'
require 'absolute_renamer/interpreters/simple_interpreter'
